- .travis.yml
- recipe/build.sh
- recipe/meta.yaml
- recipe/no_compile_setup.patch
This is not working. Just sending the PR so we can have a log of the issue.
Closes #1
> Build OS X

- recipe/meta.yaml
See http://scitools.org.uk/iris/docs/v1.12.0/whatsnew/1.12.html
> Updated to 1.12.0

- appveyor.yml
- ci_support/run_docker_build.sh
- recipe/meta.yaml
- recipe/pandas.patch
Just while we wait for the next release.
> Patch for latest pandas

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.5.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.5.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/win_python2.7.yaml
- .ci_support/win_python3.5.yaml
- .ci_support/win_python3.6.yaml
- recipe/meta.yaml
> unpin netcdf4

- recipe/meta.yaml
> removed iris-grib dependency

- recipe/meta.yaml
> updated iris recipe to v2.2

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Update for Iris v2.3.0.

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/linux_python3.7.yaml
- .ci_support/linux_python3.8.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/osx_python3.7.yaml
- .ci_support/osx_python3.8.yaml
- .ci_support/win_python2.7.yaml
- .ci_support/win_python3.6.yaml
- .ci_support/win_python3.7.yaml
- .ci_support/win_python3.8.yaml
- conda-forge.yml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> iris 2.4.0rc0

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/linux_python3.7.yaml
- .ci_support/linux_python3.8.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/osx_python3.7.yaml
- .ci_support/osx_python3.8.yaml
- .ci_support/win_python2.7.yaml
- .ci_support/win_python3.6.yaml
- .ci_support/win_python3.7.yaml
- .ci_support/win_python3.8.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Iris 2.4.0

- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.6.____cpython.yaml
- .ci_support/osx_64_python3.7.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/win_64_python3.6.____cpython.yaml
- .ci_support/win_64_python3.7.____cpython.yaml
- .ci_support/win_64_python3.8.____cpython.yaml
- .ci_support/win_64_python3.9.____cpython.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
The changes I reverted here should be only on the rc branch.
> Fix master publication

- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .scripts/run_docker_build.sh
- recipe/meta.yaml
> iris release v3.0.0

- recipe/meta.yaml
> bump for 3.0.1

- README.md
- recipe/meta.yaml
> update about:home url

- .azure-pipelines/azure-pipelines-linux.yml
- recipe/meta.yaml
I ran into an issue where I was creating an env with iris 3.0.2 and cf_units 2.1.3 and it was failing. I thought we should add a min pin
Checklist
* ~[ ] Reset the build number to `0` (if the version changed)~
> Update the min pin of cf_units to 2.1.5

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/win_64_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- build-locally.py
- recipe/meta.yaml
I have based these changes of what was done in #55 
Checklist
> Build for Iris 3.1.0rc0

- .azure-pipelines/azure-pipelines-win.yml
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
> Updated for v3.1.0.

- recipe/meta.yaml
> Bumpy version to 3.2.0.post0

- .circleci/config.yml
- .scripts/build_steps.sh
- LICENSE.txt
- README.md
- build-locally.py
- recipe/meta.yaml
> temporary min pin

- recipe/meta.yaml
> Update to v3.3.1

- .circleci/config.yml
- .scripts/build_steps.sh
- recipe/meta.yaml
> Recipe changes for 3.4.0rc0.

- .circleci/config.yml
- .scripts/build_steps.sh
- recipe/meta.yaml
> Recipe changes for v3.4.0.

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Recipe updates for v3.4.1

- .github/CODEOWNERS
- .scripts/build_steps.sh
- README.md
- recipe/meta.yaml
> Recipe updates for v3.5.0rc0 .

- recipe/meta.yaml
> Recipe updates for v3.6.0rc0

- recipe/meta.yaml
> Recipe updates for v3.6.0

- recipe/meta.yaml
> release v3.6.1

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Update to v3.7.0rc0

- .azure-pipelines/azure-pipelines-linux.yml
- recipe/meta.yaml
> Recipe updates for v3.7.0 .

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- .gitignore
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
**Includes the license change - #104 - although that cannot be closed until this gets onto `main`.**
Note the inclusion of the `conda_build_config.yaml` change [as documented here](https://conda-forge.org/docs/maintainer/knowledge_base/#pre-release-builds).
Checklist
* ~~[ ] Bumped the build number (if the version is unchanged)~~
> Recipe updates for v3.8.0rc0

- README.md
- recipe/meta.yaml
Checklist
* ~~Bumped the build number (if the version is unchanged)~~
This diff should demonstrate that the recipe has the MINIMUM differences with `v3.7.0` (i.e. it retains the old LGPL licence and dependency pins):
https://github.com/conda-forge/iris-feedstock/compare/784c731bdb3cb37833de330bbc700df905d9bcea...52b0a9f
> Recipe updates for v3.7.1

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
Checklist
@HGWright missed the email invitation the first time round.
> Re-instate @HGWright as a maintainer

- .ci_support/linux_64_.yaml
- .github/CODEOWNERS
- README.md
- azure-pipelines.yml
- recipe/meta.yaml
> Recipe updates for v3.11.0 .

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- build-locally.py
- recipe/meta.yaml
> Recipe updates for v3.11.1 .

- .ci_support/linux_64_.yaml
- .gitignore
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> V3.12.0rc0

- .gitignore
- recipe/meta.yaml
> Recipe changes for v3.12.0 release.
